export enum UserTypes {
  ROLE_MASTER = 'ROLE_MASTER',
  ROLE_CUSTOMER = 'ROLE_CUSTOMER',
  ROLE_SELLER = 'ROLE_SELLER',
  ROLE_ADMIN = 'ROLE_ADMIN',
  ROLE_DOCTOR = 'ROLE_DOCTOR',
  ROLE_CUSTOMER_CARE = 'ROLE_CUSTOMER_CARE',
  ROLE_RAIDER = 'ROLE_RAIDER',
  ROLE_GUEST = 'ROLE_GUEST'
}
